# Generated by Django 5.0.6 on 2024-06-27 03:28

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=150, unique=True)),
                ('category_img', models.ImageField(null=True, upload_to='media/category_img')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=150, unique=True)),
                ('company_owner_name', models.CharField(max_length=150, null=True)),
                ('company_owner_email', models.CharField(max_length=150, null=True, unique=True)),
                ('company_owner_phone', models.CharField(max_length=150, null=True)),
                ('company_address', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('offer_code', models.CharField(max_length=150, null=True, unique=True)),
                ('offer_rate', models.IntegerField(null=True)),
                ('offer_required_amount', models.IntegerField(null=True)),
                ('offer_description', models.TextField()),
                ('offer_img', models.ImageField(null=True, upload_to='media/offer_img')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('profile_pic', models.ImageField(null=True, upload_to='media/profile_pic')),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('bod', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, max_length=150, null=True)),
                ('user_type', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=2)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('delivery_address_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('delivery_address', models.TextField(null=True)),
                ('delivery_address_pincode', models.CharField(max_length=10, null=True)),
                ('address_type', models.CharField(choices=[(1, 'Primary Address'), (1, 'Secondary Address')], default=1, max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('feedback_message', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('notification_message', models.TextField(blank=True, null=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('order_amount', models.CharField(max_length=20)),
                ('order_discount_price', models.CharField(max_length=20, null=True)),
                ('order_total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('shipping_price', models.DecimalField(blank=True, decimal_places=2, default=10.0, max_digits=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('order_delivery_address', models.TextField(blank=True, null=True)),
                ('order_delivery_address_pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('order_status', models.CharField(default='Order Confirmed', max_length=50)),
                ('order_tracking_id', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('order_detail_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=150, null=True)),
                ('product_quantity', models.IntegerField(null=True)),
                ('product_price', models.IntegerField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_supplement_app.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('payment_amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=150)),
                ('payment_status', models.CharField(max_length=150)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine_supplement_app.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('prescription_img', models.ImageField(null=True, upload_to='media/prescription_img')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription_Detail',
            fields=[
                ('prescription_detail_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('prescription_message', models.CharField(blank=True, max_length=150, null=True)),
                ('prescription_status', models.CharField(default='Pending For Approve', max_length=100)),
                ('order_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_supplement_app.order_detail')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_supplement_app.prescription')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=150, unique=True)),
                ('product_img', models.ImageField(null=True, upload_to='media/prduct_img')),
                ('product_description', models.TextField(null=True)),
                ('product_price', models.IntegerField()),
                ('product_discount_price', models.IntegerField(null=True)),
                ('product_quantity', models.IntegerField()),
                ('product_expirydate', models.DateField()),
                ('product_weight', models.CharField(blank=True, max_length=150)),
                ('product_madein', models.CharField(blank=True, max_length=150)),
                ('product_advantage', models.TextField(blank=True)),
                ('product_disadvantage', models.TextField(blank=True)),
                ('product_prescription_status', models.IntegerField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_supplement_app.company')),
            ],
        ),
        migrations.AddField(
            model_name='order_detail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_supplement_app.product'),
        ),
        migrations.CreateModel(
            name='Cart_Detail',
            fields=[
                ('cart_detail_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cart_quantity', models.IntegerField(default=1, null=True)),
                ('cart_product_price', models.IntegerField(null=True)),
                ('cart_total_price', models.IntegerField(blank=True, null=True)),
                ('prescription_status', models.IntegerField()),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_supplement_app.cart')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_supplement_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('subcategory_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=150, unique=True)),
                ('subcategory_img', models.ImageField(null=True, upload_to='media/category_img')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_supplement_app.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_supplement_app.sub_category'),
        ),
    ]
