# Generated by Django 5.0.6 on 2024-06-27 04:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_supplement_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Review',
            fields=[
                ('product_review_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_review_message', models.TextField(blank=True, null=True)),
                ('product_rating', models.IntegerField(choices=[(1, '⭐☆☆☆☆'), (2, '⭐⭐☆☆☆'), (3, '⭐⭐⭐☆☆'), (4, '⭐⭐⭐⭐☆'), (5, '⭐⭐⭐⭐⭐')], default=None)),
                ('product_review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='medicine_supplement_app.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
