# Generated by Django 5.0.6 on 2024-06-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_supplement_app', '0002_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
