# Generated by Django 5.0.6 on 2024-06-28 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_supplement_app', '0004_payment_razorpay_order_id_alter_payment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
    ]
