# Generated by Django 5.0.6 on 2024-06-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_supplement_app', '0005_remove_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
